# Generated by Django 2.2.7 on 2019-11-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191118_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], max_length=10, null=True),
        ),
    ]
